# Generated by Django 5.1 on 2024-09-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("request_method", models.CharField(max_length=10)),
                ("request_uri", models.CharField(max_length=255)),
                ("status_code", models.IntegerField()),
                ("bytes_sent", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
