version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: log_parser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  app:
    build: .
    container_name: log_parser
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
